# Generated by Django 3.2 on 2021-06-03 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import republics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('since', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('type', models.CharField(choices=[('1', 'Feminina'), ('2', 'Masculina'), ('3', 'Mista')], max_length=10)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(null=True, upload_to=republics.models.path_and_rename)),
                ('has_animal', models.BooleanField(default=False)),
                ('has_3d_printer', models.BooleanField(default=False)),
                ('has_garage', models.BooleanField(default=False)),
                ('has_grill', models.BooleanField(default=False)),
                ('has_internet', models.BooleanField(default=False)),
                ('has_maid', models.BooleanField(default=False)),
                ('has_pool', models.BooleanField(default=False)),
                ('has_snooker', models.BooleanField(default=False)),
                ('has_washing_machine', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
