# Generated by Django 3.1.3 on 2020-12-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('republics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rep',
            name='has_3d_printer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rep',
            name='has_animal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rep',
            name='has_garage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rep',
            name='has_grill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rep',
            name='has_internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rep',
            name='has_maid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rep',
            name='has_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rep',
            name='has_snooker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rep',
            name='has_washing_machine',
            field=models.BooleanField(default=False),
        ),
    ]
