# Generated by Django 3.1.3 on 2020-12-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('republics', '0002_auto_20201213_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='rep',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
