version: '3'
services:
  web:
    build: .
    ports:
      - "80:8000"
    environment:
      - DEBUG: ${DEBUG}
      - SECRET_KEY: ${SECRET_KEY}
      - ALLOWED_HOSTS: ${ALLOWED_HOSTS}

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080